export const CurrencyTypes = {
    FETCH_CURRENCY_START: 'FETCH_CURRENCY_START',
    FETCH_CURRENCY_SUCCESS: 'FETCH_CURRENCY_SUCCESS',
    FETCH_CURRENCY_FAILURE: 'FETCH_CURRENCY_FAILURE',
    EDIT_DATA: 'EDIT_DATA'
}
